### ISSUE TITLE
Question: Is there a way for the replacement text to contain a newline character?

### ISSUE THREAD

**Issue by claremacrae** [Gru80/obsidian-regex-replace#1]
This looks like it will be really useful - thank you!

I recently had a paragraph of text I had copied, and wanted to convert all `. ` to `.\n` - where `\n` is a newline character:

Something like:

`s|\. |.\n|g'`

Is that possible with this plugin?

I realise there may be the complication of putting in newlines that are consistent with the current file's existing content... I don't know how Obsidian manages different line endings when syncing across Unix and Windows...

**Comment by Gru80** [comment]
Good one! 
Actually, right now escape characters in the _Replace_ field are not processed - so basically `\n` is literally interpreted as the two characters `\` and `n`. 

Having said that, for a future version it's definitely worth considering to have an option which allows to handle escape characters as such (maybe as setting in a dedicated Plugin-Settings page in order keep the Find/Replace dialog slim, not overloading it with too many toggle-switches).

**Comment by Gru80** [comment]
@claremacrae With the latest commit in the develop-branch an option has been introduced which allows to interpret "\n" in the replace-field - a line-break is inserted at these positions accordingly
![image](https://user-images.githubusercontent.com/30384872/145690479-05a6346f-b4f6-4a2a-9128-6f4cb1c4b450.png)
This option (along with some others) will be part of release 1.2.0

**Comment by kabo1234** [comment]
Hi,

I'm also looking for a way to have a new line in the replacement - any idea when 1.2.0 will be released?

Many thanks!

**Comment by Gru80** [comment]
Hi,
should not take too long actually, I just need to do some more testing to verify the latest changes in the code

**Comment by m-radzikowski** [comment]
Until this is released, if both the find and replace contain new lines, a workaround is to use capturing group:

For example, to replace two newlines with one:

Find: `(\n)\n`  
Replace: `$1`

**Comment by kabo1234** [comment]
> Until this is released, if both the find and replace contain new lines, a workaround is to use capturing group:
> 
> For example, to replace two newlines with one:
> 
> Find: `(\n)\n` Replace: `$1`

Thanks - but 1.2.0 was just released!

Thanks @Gru80

**Comment by Stefanando** [comment]
Thanks, it is a very useful plugin! I don't know if you still develop it, anyway I remarked that when you try to replace all it works also inside the properties field, and if I ask to replace a "-" with a "\n" the properties area is messed
