### ISSUE TITLE
Is there a non-capture function?

### ISSUE THREAD

**Issue by jaymaleoca** [Gru80/obsidian-regex-replace#16]
Hi there Martin, 

Thank you for the plugin. This has been tremendously helpful, especially reviewing my old notes and imports from other platforms.

Wondering if there is a non-capture function... I have tried using `(?:xxx)`, xxx being where to skip over but it hasn't worked for me. I am trying to delete the external links in markdown `\[(?:\w+)\]\(https?\:\/\/.+?\)`  so that `[site](https://website.com)` will be rewritten to `site` only.

If there is something obvious that I overlooked, please let me know that as well!

Thank you,
Jason

**Comment by jaymaleoca** [comment]
I figured a workaround where I could use `captured group` with `$<group number>` syntax as a replacement for the initial search!

So, the `(\[)(.+?)(\]\(https?\:\/\/[a-zA-Z0-9_\.\/-]+\))` is replaced with `$2`... which is `(.+?)` which is capturing `site` from `[site](https://site.com)` while deleting the others.

Anyway, posting this for others who might be thinking about the same question.

Thanks againg for the plugin!

**Comment by Gru80** [comment]
thanks for sharing!
