### ISSUE TITLE
Remove certain characters in a string

### ISSUE THREAD

**Issue by VK5675** [Gru80/obsidian-regex-replace#28]
I have a note or markdown file in obsidian 

In that note, I  want to use replace all command to replace t=25s, t=95s, t=180s with t=25, t=95, t-180. I need to get rid of s

What command can i do in regex find/replace to achieve the above.

**Comment by Gru80** [comment]
Although this question is not really related to the plugin itself or its code, the following term should work:

Find: `t=(\d+)s`
Replace: `t=$1`
