### ISSUE TITLE
Regular expression error

### ISSUE THREAD

**Issue by kazdonkai** [Gru80/obsidian-regex-replace#5]
As shown in the image, an error occurs in the regular expression conversion.
![7F5C5BB7-A6A4-4B17-BC3D-A164ECEB3477](https://user-images.githubusercontent.com/90127278/150661201-83f70872-5168-4f80-bf64-b93ee0c69c64.jpeg)

**Comment by Gru80** [comment]
Hi,
this is not an issue with the plugin, but an actual behavior of regular expressions:
[Here is a link to your sample at regex101](https://regex101.com/r/XWEtEo/1) - it results in the same output

**Comment by kazdonkai** [comment]
Thank you very much for your quick response.
I did as in the image and it worked.

It would be useful for others if you could write the basic notation and an example like this in the referrance.

![3B568F55-2DD5-4FB0-B0FF-1D9C47D842E7](https://user-images.githubusercontent.com/90127278/151696772-13ef2799-7819-41a1-b182-42b65cc88761.jpeg)
